apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart-dev

resources:
- ../../base
- ./sealed-postgresql-secret.yaml


patches:
- path: namespace-patch.yaml
- path: configmap-patch.yaml
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: cloudcart-ingress
    version: v1
images:
- name: ghcr.io/mohitbnt/cloudcart-cart
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-catalog
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-frontend
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-gateway
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-identity
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-inventory
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-notification
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-order
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
- name: ghcr.io/mohitbnt/cloudcart-payment
  newTag: 889f732ff20a1962dc600c3909a75d7b31a27d03
