apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart-dev

resources:
  - ../../base

patches:
  - path: namespace-patch.yaml
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: cloudcart-ingress
    path: ingress-patch.yaml

images:
  - name: ghcr.io/mohitbnt/cloudcart-catalog
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-identity
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-cart
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-inventory
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-order
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-payment
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-notification
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-gateway
    newTag: dev-1.0.0

  - name: ghcr.io/mohitbnt/cloudcart-frontend
    newTag: dev-1.0.0