apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-netpol
  labels:
    app.kubernetes.io/name: frontend-netpol
    app.kubernetes.io/instance: cloudcart-frontend-netpol
    app.kubernetes.io/component: network-policy
    app.kubernetes.io/part-of: cloudcart
    app.kubernetes.io/managed-by: kustomize
  namespace: cloudcart
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/instance: cloudcart-frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/instance: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/instance: ingress-nginx
      ports:
        - protocol: TCP
          port: 80