apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart-prod

resources:
  - ../../base

patches:
  - path: namespace-patch.yaml

images:
  - name: public.ecr.aws/k3e1b3j2/cloudcart/catalog
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/identity
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/cart
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/inventory
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/order
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/payment
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/notification
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/gateway
    newTag: prod-1.0.0

  - name: public.ecr.aws/k3e1b3j2/cloudcart/frontend
    newTag: prod-1.0.0