apiVersion: v1
kind: Namespace

metadata:
  name: cloudcart
  labels:
    app.kubernetes.io/name: cloudcart
    app.kubernetes.io/instance: cloudcart-prod
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: cloudcart
    app.kubernetes.io/managed-by: kustomize