apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart-prod

resources:
  - ../../base

patches:
  - path: namespace-patch.yaml

images:
  - name: ghcr.io/mohitbnt/cloudcart-catalog
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-identity
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-cart
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-inventory
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-order
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-payment
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-notification
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-gateway
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd

  - name: ghcr.io/mohitbnt/cloudcart-frontend
    newTag: 163810200a511c30519ee2b0c343a384f08d6afd