apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudcart-prod
  namespace: argocd
spec:
  description: "Cloudcart Production Environment"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: cloudcart-prod
      server: '*'
  sourceRepos:
    - 'https://github.com/mohitbnt/cloudcart-k8s.git'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudcart-dev
  namespace: argocd
spec:
  description: "Cloudcart Development Environment"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: cloudcart-dev
      server: '*'
  sourceRepos:
    - 'https://github.com/mohitbnt/cloudcart-k8s.git'