apiVersion: v1
kind: Secret
metadata:
  name: cloudcart-secret
  namespace: cloudcart
  labels:
    app.kubernetes.io/name: cloudcart
    app.kubernetes.io/instance: cloudcart-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: cloudcart
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  POSTGRES_USER: cloudcart_user
  POSTGRES_PASSWORD: cloudcart_password
  POSTGRES_DB: cloudcart_db
  POSTGRES_HOST: cloudcart-postgresql-service
  POSTGRES_PORT: "5432"
  DATABASE_URL: postgresql+psycopg://cloudcart_user:cloudcart_password@cloudcart-postgresql-service:5432/cloudcart_db